Server ignores comments in smt input
Until now in case of a comment line the message
  ERROR: Parsing failed!
  Stop at: <comment>
was printed. This is removed